Add an option to save action output to a file

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,15 +7,22 @@ jobs:
     runs-on: ubuntu-latest
     name: Test diff action
     steps:
-        - name: checkout
-          uses: actions/checkout@v4
-        - name: Running diff action
-          id: test_ete
-          uses: ./diff
-          with:
-            base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
-            revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
-            format: 'text'
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Running diff action
+        id: test_ete
+        uses: ./diff
+        with:
+          base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
+          revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
+          format: 'text'
+          output-to-file: 'diff.txt'
+      - name: Test diff action output to file
+        run: |
+          if [ ! -s diff.txt ]; then
+            echo "Diff file doesn't exist or is empty"
+            exit 1
+          fi
   oasdiff_diff_exclude_elements:
     runs-on: ubuntu-latest
     name: Test diff action with exclude-elements option
@@ -54,6 +61,7 @@ jobs:
           base: 'specs/base.yaml'
           revision: 'specs/revision-breaking.yaml'
           fail-on-diff: false
+          output-to-file: 'breaking.txt'
       - name: Test breaking changes action output
         run: |
           delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
@@ -62,7 +70,18 @@ jobs:
           $delimiter
           )
           if [ "$output" != "1 breaking changes: 1 error, 0 warning" ]; then
-            echo "Expected output '6 breaking changes: 2 error, 4 warning' but got '$output'" >&2
+            echo "Expected output '1 breaking changes: 1 error, 0 warning' but got '$output'" >&2
+            exit 1
+          fi
+      - name: Test breaking changes action output to file
+        run: |
+          if [ ! -s breaking.txt ]; then
+            echo "Breaking changes file doesn't exist or is empty"
+            exit 1
+          fi
+          output=$(cat breaking.txt)
+          if [[  "${output}" != "1 breaking changes: 1 error, 0 warning" ]]; then
+            echo "Expected output '1 breaking changes: 1 error, 0 warning' but got '${output}'" >&2
             exit 1
           fi
   oasdiff_breaking_deprecation:
@@ -98,6 +117,7 @@ jobs:
         with:
           base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
           revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
+          output-to-file: "changelog.txt"
       - name: Test changelog action output
         run: |
           readonly expected_output="20 changes: 2 error, 4 warning, 14 info"
@@ -105,4 +125,15 @@ jobs:
           if [[  "${output}" != "${expected_output}" ]]; then
             echo "Expected output '20 changes: 2 error, 4 warning, 14 info' but got '${output}'" >&2
             exit 1
-          fi  
+          fi
+      - name: Test changelog action output to file
+        run: |
+          if [ ! -s changelog.txt ]; then
+            echo "Changelog file doesn't exist or is empty"
+            exit 1
+          fi
+          output=$(cat changelog.txt | head -n 1)
+          if [[  "${output}" != "20 changes: 2 error, 4 warning, 14 info" ]]; then
+            echo "Expected output '20 changes: 2 error, 4 warning, 14 info' but got '${output}'" >&2
+            exit 1
+          fi
