output

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -1,4 +1,4 @@
-name: 'Test OpenAPI Spec Diff Action'
+name: 'Test oasdiff actions'
 on:
   pull_request:
   push:
@@ -28,7 +28,15 @@ jobs:
         with:
           base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
           revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
-          fail-on-diff: true
+          fail-on-diff: false
+      - name: Test breaking changes output
+        run: |
+          output=$(cat ${{ steps.test_breaking_changes.outputs.breaking }})
+          echo $output
+          if [ -z "$output" ]; then
+            echo "Missing output from action" >&2
+            exit 1
+          fi
   oasdiff_breaking_deprecation:
     runs-on: ubuntu-latest
     name: Test breaking changes with deprecation
@@ -58,7 +66,7 @@ jobs:
         uses: actions/checkout@v3
       - name: Running changelog action
         id: test_changelog
-        uses: oasdiff/oasdiff-action/changelog@v0.0.10
+        uses: ./changelog
         with:
           base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
           revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
