GitHub Action Output Part 4: changelog output (#30)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -73,3 +73,11 @@ jobs:
         with:
           base: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test1.yaml
           revision: https://raw.githubusercontent.com/Tufin/oasdiff/main/data/openapi-test3.yaml
+      - name: Test changelog action output
+        run: |
+          readonly expected_output="20 changes: 2 error, 4 warning, 14 info"
+          output=$(echo "${{steps.test_changelog.outputs.changelog}}" | head -n 1)
+          if [[  "${output}" != "${expected_output}" ]]; then
+            echo "Expected output '20 changes: 2 error, 4 warning, 14 info' but got '${output}'" >&2
+            exit 1
+          fi  
