fix: removing fail-on-diff and defaulting to oasdiff param of fail-on - updating tests, etc.

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -53,7 +53,7 @@ jobs:
         with:
           base: 'specs/base.yaml'
           revision: 'specs/revision-breaking.yaml'
-          fail-on-diff: false
+          fail-on: 'WARN'
       - name: Test breaking changes action output
         run: |
           delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
@@ -62,7 +62,7 @@ jobs:
           $delimiter
           )
           if [ "$output" != "1 breaking changes: 1 error, 0 warning" ]; then
-            echo "Expected output '6 breaking changes: 2 error, 4 warning' but got '$output'" >&2
+            echo "Expected output '1 breaking changes: 1 error, 0 warning' but got '$output'" >&2
             exit 1
           fi
   oasdiff_breaking_deprecation:
@@ -83,24 +83,23 @@ jobs:
         with:
           base: specs/base.yaml
           revision: specs/base-deprecation.yaml
-          fail-on-diff: true
+          fail-on: 'WARN'
           deprecation-days-beta: 14
           deprecation-days-stable: 21
-  oasdiff_breaking_fail_on_explicit:
+  oasdiff_breaking_fail_on_err:
     runs-on: ubuntu-latest
-    name: Test breaking changes fail-on
+    name: Test breaking changes fail-on (ERR)
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: Running breaking action
-        id: test_breaking_changes
+        id: test_breaking_changes_err
         uses: ./breaking
         with:
           base: 'specs/base.yaml'
           revision: 'specs/revision-breaking.yaml'
-          fail-on-diff: false 
-          fail-on: ERR
-      - name: Test breaking changes action output
+          fail-on: 'ERR'
+      - name: Test breaking changes action output (ERR)
         run: |
           delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
           output=$(cat <<-$delimiter
@@ -108,7 +107,31 @@ jobs:
           $delimiter
           )
           if [ "$output" != "1 breaking changes: 1 error, 0 warning" ]; then
-            echo "Expected output '6 breaking changes: 2 error, 4 warning' but got '$output'" >&2
+            echo "Expected output '1 breaking changes: 1 error, 0 warning' but got '$output'" >&2
+            exit 1
+          fi
+  oasdiff_breaking_fail_on_warn:
+    runs-on: ubuntu-latest
+    name: Test breaking changes fail-on (WARN)
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Running breaking action
+        id: test_breaking_changes_err
+        uses: ./breaking
+        with:
+          base: 'specs/base.yaml'
+          revision: 'specs/revision-breaking-warning.yaml'
+          fail-on: 'ERR'
+      - name: Test breaking changes action output (WARN) - Expecting No Output
+        run: |
+          delimiter=$(cat /proc/sys/kernel/random/uuid | tr -d '-')
+          output=$(cat <<-$delimiter
+          ${{ steps.test_breaking_changes.outputs.breaking }}
+          $delimiter
+          )
+          if [ -n "$output" ]; then
+            echo "Expected no breaking output as the fail-on level is set to ERR (error) and there should only be warnings' but got '$output'" >&2
             exit 1
           fi
   oasdiff_changelog:
