improve test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -36,8 +36,8 @@ jobs:
           ${{ steps.test_breaking_changes.outputs.breaking }}
           $delimiter)
           echo $output
-          if [ -z "$output" ]; then
-            echo "Missing output from action" >&2
+          if [ "$output" != "6 breaking changes: 2 error, 4 warning"]; then
+            echo "Expected output '6 breaking changes: 2 error, 4 warning' but got '$output'" >&2
             exit 1
           fi
   oasdiff_breaking_deprecation:
